<a href="https://colab.research.google.com/github/bhanwarlalsaini/getting-started-with-pandas/blob/master/getting_started_with_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd 
df = pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})
df

   Yes   No
0   50  131
1   21    2

In [ ]:
df1 = pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']})
df1

             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.

In [ ]:
s1 = pd.Series([1, 2, 3, 4, 5])
print(s1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
s2 = pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')
s2

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

In [ ]:
from google.colab import drive 
drive.mount("/content/drive")

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive

In [ ]:
file = pd.read_csv("/content/drive/My Drive/winemag-data-130k-v2.csv")

In [ ]:
file.head()

   Unnamed: 0   country  ...         variety               winery
0           0     Italy  ...     White Blend              Nicosia
1           1  Portugal  ...  Portuguese Red  Quinta dos Avidagos
2           2        US  ...      Pinot Gris            Rainstorm
3           3        US  ...        Riesling           St. Julian
4           4        US  ...      Pinot Noir         Sweet Cheeks

[5 rows x 14 columns]

In [ ]:
file.iloc[0]

Unnamed: 0                                                               0
country                                                              Italy
description              Aromas include tropical fruit, broom, brimston...
designation                                                   Vulkà Bianco
points                                                                  87
price                                                                  NaN
province                                                 Sicily & Sardinia
region_1                                                              Etna
region_2                                                               NaN
taster_name                                                  Kerin O’Keefe
taster_twitter_handle                                         @kerinokeefe
title                                    Nicosia 2013 Vulkà Bianco  (Etna)
variety                                                        White Blend
winery                                                             Nicosia
Name: 0, dtype: object

In [ ]:
file.iloc[:, 1]

0            Italy
1         Portugal
2               US
3               US
4               US
            ...
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [ ]:
file.iloc[:3, 1]

0       Italy
1    Portugal
2          US
Name: country, dtype: object

In [ ]:
file.iloc[1:3, 1]

1    Portugal
2          US
Name: country, dtype: object

In [ ]:
file.loc[0, 'country']

'Italy'

In [ ]:
file.loc[:, ['taster_name', 'taster_twitter_handle', 'points']]

               taster_name taster_twitter_handle  points
0            Kerin O’Keefe          @kerinokeefe      87
1               Roger Voss            @vossroger      87
2             Paul Gregutt           @paulgwine       87
3       Alexander Peartree                   NaN      87
4             Paul Gregutt           @paulgwine       87
...                    ...                   ...     ...
129966  Anna Lee C. Iijima                   NaN      90
129967        Paul Gregutt           @paulgwine       90
129968          Roger Voss            @vossroger      90
129969          Roger Voss            @vossroger      90
129970          Roger Voss            @vossroger      90

[129971 rows x 3 columns]

In [ ]:
file.loc[(file.country == 'Italy') & (file.points >= 90)]

        Unnamed: 0 country  ...       variety                           winery
120            120   Italy  ...      Nebbiolo                          Ceretto
130            130   Italy  ...      Nebbiolo                          Ceretto
133            133   Italy  ...      Nebbiolo             Poderi Luigi Einaudi
135            135   Italy  ...      Nebbiolo                  Giacomo Ascheri
140            140   Italy  ...       Barbera                     Poderi Colla
...            ...     ...  ...           ...                              ...
129929      129929   Italy  ...      Prosecco             Col Vetoraz Spumanti
129943      129943   Italy  ...     Red Blend  Baglio del Cristo di Campobello
129947      129947   Italy  ...     Red Blend         Feudo Principi di Butera
129961      129961   Italy  ...      Frappato                              COS
129962      129962   Italy  ...  Nero d'Avola                         Cusumano

[6648 rows x 14 columns]

In [ ]:
file.loc[(file.country == 'Italy') | (file.points >= 90)]

        Unnamed: 0  ...                                    winery
0                0  ...                                   Nicosia
6                6  ...                           Terre di Giurfo
13              13  ...                       Masseria Setteporte
22              22  ...                        Baglio di Pianetto
24              24  ...                                 Canicattì
...            ...  ...                                       ...
129966      129966  ...  Dr. H. Thanisch (Erben Müller-Burggraef)
129967      129967  ...                                  Citation
129968      129968  ...                           Domaine Gresser
129969      129969  ...                      Domaine Marcel Deiss
129970      129970  ...                          Domaine Schoffit

[61937 rows x 14 columns]

In [ ]:
file.loc[file.price.notnull()]

        Unnamed: 0  ...                                    winery
1                1  ...                       Quinta dos Avidagos
2                2  ...                                 Rainstorm
3                3  ...                                St. Julian
4                4  ...                              Sweet Cheeks
5                5  ...                                    Tandem
...            ...  ...                                       ...
129966      129966  ...  Dr. H. Thanisch (Erben Müller-Burggraef)
129967      129967  ...                                  Citation
129968      129968  ...                           Domaine Gresser
129969      129969  ...                      Domaine Marcel Deiss
129970      129970  ...                          Domaine Schoffit

[120975 rows x 14 columns]